export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const FETCH_PRODUCT_DETAIL_SUCCESS  = 'FETCH_PRODUCT_DETAIL_SUCCCESS';
export const FETCH_PRODUCT_DETAIL_FAILURE  = 'FETCH_PRODUCT_DETAIL_FAILURE';

export const TOGGLE_LOADER = "TOGGLE_LOADER";
